name: testsnap
base: core18
version: '0.1.0'
summary: A test snap
description: |
  A test snap

grade: devel
confinement: devmode

parts:
  copy:
    plugin: dump
    source: .

apps:
  testsnap:
    command: testsnap
